# @format

version: 2
updates:
  - package-ecosystem: github-actions
    open-pull-requests-limit: 8
    directory: '/'
    schedule:
      interval: daily

  - package-ecosystem: docker
    open-pull-requests-limit: 1
    directory: '/'
    schedule:
      interval: daily

  - package-ecosystem: docker-compose
    open-pull-requests-limit: 2
    directory: '/'
    schedule:
      interval: daily

  - package-ecosystem: npm
    versioning-strategy: increase
    open-pull-requests-limit: 5
    directory: '/'
    schedule:
      interval: daily
